version: "3.9"
services:
  pgdatabase:
    image: postgres:13
    #container_name: postgres-music
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=music_events
    volumes:
      - "./postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5439:5432"

  pgadmin:
    image: dpage/pgadmin4
    #container_name: pgadmin-music
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8090:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  music-events-pipeline:
    build: .
    image: lucerne_music_pipeline:v0.0.1

    
volumes:
    pgadmin-data: